### ISSUE TITLE
System.NullReferenceException

### ISSUE THREAD

**Issue by NebelFox** [NebelFox/verbox#1]
Message:
```
Unhandled exception. System.NullReferenceException: Object reference not set to an instance of an object.
   at EasyCLI.Namespace.Member(ExecutableDefinition definition) in ...\EasyCLI\EasyCLI\Definitions\Executables\Namespace.cs:line 30
   at EasyCLI.MenuBuilder.Command(ExecutableDefinition definition) in ...\EasyCLI\EasyCLI\Builders\MenuBuilder.cs:line 43
   at CLIUser.Program.Main(String[] args) in ...\CLIUser\CLIUser\Program.cs:line 69
```

Menu build:
```C#
new MenuBuilder()
    .Greeting("Hi there!\nJust testing it splits correctly...")
    .Title("This is a title")
    .Header("This is a header first line\nAnd this is the second")
    .Command(new Command("print", "just prints the value")
           .Arg("value", "what to print")
           .Action(context => Console.WriteLine(context[0]))
           .Example("print 12345"))
    .Command(new Command("exit", "terminates the program")
           .Action(context => context.Source.Terminate()))
    .Footer("Forgot to add it and spend half an hour fixing a non-existent bug")
    .Farewell("See ya.")
    .Build()
    .StartDialogue();
```

**Comment by NebelFox** [comment]
Fixed in https://github.com/NebelFox/EasyCLI/commit/f4543cfdfea0555d086a48c9a9fd2b872e8ce40b
